### PR TITLE
Make PolyDet the default for fields in @HasQualifierParameter classes.

### LINKED ISSUE #115: Make default for fields @PolyDet
Currently, the default for fields is `@Det`. I believe `@PolyDet` would be best. Firstly, the default for method and constructor parameters is `@PolyDet`, meaning the following code won't type check by default:

```java
import org.checkerframework.checker.determinism.qual.*;

public class TestDefaults {
    int field;

    public TestDefaults(@PolyDet int field) {
        this.field = field;
    }
}
```
```
TestDefaults.java:8: error: [invalid.field.assignment] cannot assign into @Det field via @PolyDet expression
        this.field = field;
            ^
```

Since the default for constructor parameters is `@PolyDet`, this kind of error would come up in almost any constructor by default.

Secondly, intuitively a field should depend on the determinism of the enclosing class. So, if the enclosing class is not declared `@Det`, the most logical choice would be for the fields to be `@PolyDet` themselves.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #115.

### CODE REVIEW

File: checker/tests/determinism/DefaultField.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import org.checkerframework.checker.determinism.qual.Det;
+import org.checkerframework.checker.determinism.qual.NonDet;
+import org.checkerframework.checker.determinism.qual.PolyDet;
+import org.checkerframework.framework.qual.HasQualifierParameter;
+
+@HasQualifierParameter(NonDet.class)
```
Comment (jwaataja) [inline checker/tests/determinism/DefaultField.java]: Could you add another test case without `@HasQualifierParameter`? I don't think we have any other tests for field defaults already so now would be a good time to have that case as well.
