### PR TITLE
Fix enhanced for loop; fixes #168 and #171

### LINKED ISSUE #168: For loop type both @Det and @NonDet at same time
In this code,
```java
import org.checkerframework.checker.determinism.qual.*;
import org.checkerframework.framework.qual.*;
import java.util.*;

@HasQualifierParameter(NonDet.class)
public class C {
    public static void f(@OrderNonDet List<@Det C> list) {
        for (C s : list) {
        }
    }
}
```
I get this error
```
C.java:8: error: [enhancedfor.type.incompatible] incompatible types in enhanced for loop.
        for (C s : list) {
                   ^
  found   : @NonDet C
  required: @PolyDet C
C.java:8: error: [enhancedfor.type.incompatible] incompatible types in enhanced for loop.
        for (C s : list) {
                   ^
  found   : @Det C
  required: @PolyDet C
```

This is unexpected because it says the type should be both `@NonDet` and `@Det`. It should be `@NonDet` only.

### PR DESCRIPTION
**Pull request by jwaataja**
Fixes various issue related to enhanced for loops. Adds a method `enhancedForLoopIteratedType` to `BaseTypeVisitor` to allow checkers to modify what types of elements collections produce when iterated over. In the case of the Determinism Checker it gives that the iterated type of an `@OrderNonDet` collection is `@NonDet`.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 1]
```diff
@@ -1653,6 +1651,20 @@ protected void typeCheckVectorCopyIntoArgument(
...
+    /**
+     * Returns the type of elements {@code iterableType} would produce when iterated over. For
+     * example, when called on {@code List<@Nullable String>}, this method would return
+     * {@code @Nullable String}.
+     *
+     * @param iterableType the type being iterated over. Must be an array or a declared type that
+     *     implements {@link Iterable}.
+     * @return the type of elements {@code iterableType} produces when iterated over.
+     */
+    protected AnnotatedTypeMirror enhancedForLoopIteratedType(AnnotatedTypeMirror iterableType) {
```
Comment (smillst) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java]: This is fixing https://github.com/typetools/checker-framework/issues/2172.
