### PR TITLE
Fixes #89; replace annotation type of array component as NonDet in the upper bound of wildcard of return type of getClass

### LINKED ISSUE #89: Array getClass always creates an error
Consider this class
```java
import org.checkerframework.checker.determinism.qual.*;
import java.util.*;

public class ArrayGetClass {
    public static void f(@Det Object @Det [] arr) {
        Class<?> c = arr.getClass();
    }
}
```
I get the following error
```
ArrayGetClass.java:6: error: [invalid.array.component.type] component type (@Det) cannot be used with array type (@NonDet)
        Class<?> c = arr.getClass();
                                 ^
```
The returned class's type parameter should be the same as the Object that `getClass` was called on, which is a valid array type. So, this shouldn't be an error. I believe the issue is with the fact that the return type actually uses the erasure type, as described [here](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#getClass()). However, this is unique to arrays, the same problem doesn't occur with subtypes of `Collection`.

### PR DESCRIPTION
**Pull request by t-rasmud**

### CODE REVIEW

File: checker/tests/determinism/Issue89.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import java.util.*;
+import org.checkerframework.checker.determinism.qual.*;
+
+public class Issue89 {
+    public static void f(@Det Object @Det [] arr, @Det List<@Det Object> lst) {
+        @Det Object @Det [] local = arr;
+        System.out.println(arr.getClass());
```
Comment (smillst) [inline checker/tests/determinism/Issue89.java]: Please add an example where the type of array is something like `String[][]`.

File: checker/src/main/java/org/checkerframework/checker/determinism/DeterminismAnnotatedTypeFactory.java [hunk 2]
```diff
@@ -444,6 +445,41 @@ public boolean mayBeOrderNonDet(AnnotatedTypeMirror javaType) {
...
+
+        final AnnotatedDeclaredType returnAdt =
+                (AnnotatedDeclaredType) getClassType.getReturnType();
+        final List<AnnotatedTypeMirror> typeArgs = returnAdt.getTypeArguments();
+        final AnnotatedTypeMirror.AnnotatedWildcardType classWildcardArg =
+                (AnnotatedTypeMirror.AnnotatedWildcardType) typeArgs.get(0);
+        if (classWildcardArg.getExtendsBoundField().getKind() == TypeKind.ARRAY) {
+            AnnotatedArrayType extendsBoundArray =
+                    (AnnotatedArrayType) classWildcardArg.getExtendsBoundField();
+            new replaceTypeOnExtendsBoundArray().visitArray(extendsBoundArray, NONDET);
```
Comment (smillst) [inline checker/src/main/java/org/checkerframework/checker/determinism/DeterminismAnnotatedTypeFactory.java]: Call `visit` instead of `visitArray`.  Then you don't need the cast above.
